// AUTO-GENERATED by /tmp/audits/build_knowledge.py from vetted research agents.
// Sources: USDA PLANTS, university extension (UMN, Purdue, PSU, Cornell, Colostate, MSU), WSSA Take Action, CABI, NRCS.
// AUTO-GENERATED by /tmp/audits/build_knowledge.py from vetted research agents.
// Sources: USDA PLANTS, university extension (UMN, Purdue, PSU, Cornell, Colostate, MSU), WSSA Take Action, CABI, NRCS.
// Updated from 8_27_weedknowledge.xlsx (89 species). Removed species no longer present in source; added Common Mullein.
// Keys match the spreadsheet's commonNames column (renamed a few that carried over stale internal names, e.g. Hemp was previously keyed "Marijuana").

export type ArrivalMethod = "accident" | "purpose" | "other-species" | "native-spread";

export interface WeedArrival {
  method: ArrivalMethod;
  continent: "europe" | "asia" | "africa" | "americas" | "mediterranean";
  story: string;
}

export const WEED_ARRIVAL_KNOWLEDGE: Record<string, WeedArrival> = {
  "annual-ryegrass": {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe as a forage and cover crop; escaped managed areas via contaminated seed and has developed herbicide resistance in some populations.",
  },
  Asian_copperleaf: {
    method: "accident",
    continent: "asia",
    story:
      "Introduced from East Asia likely as a contaminant in crop or nursery material; an emerging weed spreading through row crop fields and disturbed areas.",
  },
  Asiatic_dayflower: {
    method: "accident",
    continent: "asia",
    story:
      "Introduced from East Asia via contaminated ornamental or nursery trade; spreading in gardens roadsides and row crop fields across the eastern US.",
  },
  barnyardgrass: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Eurasia via contaminated rice and crop seed; thrives in wet environments and mimics rice seedlings complicating early detection in paddies.",
  },
  Buffalobur: {
    method: "accident",
    continent: "americas",
    story:
      "Native to central North America but spread far beyond its range via contaminated grain and livestock transport; spiny fruits cling to fur and clothing.",
  },
  Burcucumber: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by spiny burs floating downstream and clinging to fur and equipment; thrives along riverbanks buffer strips and floodplains.",
  },
  "canada-thistle": {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from SE Europe and W Asia via contaminated crop seed in the 1700s; creeping roots and wind-dispersed seeds spread rapidly across farmland.",
  },
  caraway: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe and Asia as a culinary and medicinal herb; escaped cultivation via contaminated hay and grain naturalizing in roadsides and pastures.",
  },
  Catchweed_bedstraw: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native winter annual spreading by bristly fruits clinging to clothing fur and machinery; forms dense mats in crop fields gardens and vineyards.",
  },
  "common-ragweed": {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by abundant seeds dispersed by birds water and farm equipment; herbicide-resistant populations rapidly colonize disturbed crop fields.",
  },
  Common_Burdock: {
    method: "other-species",
    continent: "europe",
    story:
      "Introduced from Europe via ship ballast and contaminated seed; hooked burrs cling to fur feathers and clothing dispersing seeds into woodlands and fields.",
  },
  common_Cocklebur: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by two-chambered spiny burs clinging to livestock fur machinery and water; colonizes cropland roadsides and river bottoms.",
  },
  Common_copperleaf: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native North American annual that moved out of woodland edges into crop fields and gardens; seeds spread by tillage water and equipment.",
  },
  Common_Mallow: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe and Asia via contaminated seed; cheese-wheel fruits release seeds that persist in soil and spread through lawns and disturbed areas.",
  },
  common_Milkweed: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by wind-dispersed silky seeds and rhizomes; colonizes fields roadsides and prairies; vital host plant for monarch butterflies.",
  },
  Common_Morningglory: {
    method: "purpose",
    continent: "americas",
    story:
      "Introduced from tropical Mexico as an ornamental; escaped cultivation and spread via contaminated crop seed into row crops across the eastern United States.",
  },
  Common_Mullein: {
    method: "purpose",
    continent: "europe",
    story:
      "Brought to US due to its medical properties; escaped gardens and spread across the continent is roadsides and open field areas.",
  },
  Common_Sunflower: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual germinating from seeds left after sunflower crops bird feeders or wildlife; competes vigorously with subsequent crops for light and nutrients.",
  },
  Common_teasel: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe for use in wool carding; escaped cultivation and spread via wind-dispersed seeds along roadsides and disturbed meadows and fields.",
  },
  CommonChickweed: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated seed; prolific winter annual producing thousands of seeds spread by birds water and agricultural equipment.",
  },
  commonPokeweed: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading primarily by bird-dispersed berries; birds eat the fruit and deposit seeds widely across pastures fencerows and open fields.",
  },
  Corn_speedwell: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated crop and garden seed; a compact winter annual spreading through gardens roadsides and small grain fields.",
  },
  Curly_dock: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe in ship ballast and contaminated seed; long-lived seeds and deep taproot enable persistence across roadsides and disturbed fields.",
  },
  Dandelion: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe by early settlers as a food and medicinal plant; wind-dispersed seeds spread rapidly across lawns gardens and pastures.",
  },
  Downy_brome: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Eurasia in contaminated hay and crop seed; wind-dispersed seeds and early germination aid rapid spread into disturbed rangelands.",
  },
  Eastern_black_nightshade: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by prolific seed dispersal; birds eat and disperse berries aiding spread through crop fields gardens and disturbed areas.",
  },
  Fall_Panicum: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual that spreads via prolific seed production; seeds moved by farm equipment water and wind across disturbed cropland and roadsides.",
  },
  Field_bindweed: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe in contaminated crop seed; rhizomes reaching 14 feet deep and long-lived seeds make it one of the most difficult weeds to control.",
  },
  Field_Horsetail: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by spores and deep rhizomes; thrives in wet soils and ditches; few herbicides are effective and drainage improvement is key.",
  },
  Field_Pennycress: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe in contaminated grain; round flat seed pods shed 20000+ seeds per plant spread by harvesting equipment and water movement.",
  },
  Foxtail_barley: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by prolific seed; sharp awns cling to livestock fur and clothing aiding dispersal across pastures and disturbed soils.",
  },
  Garlic_mustard: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe as a food plant; allelopathic and invasive in forest under spreading via thousands of seeds dispersed by water and footwear.",
  },
  "giant-foxtail": {
    method: "accident",
    continent: "asia",
    story:
      "Introduced from China as a contaminant in millet seed in the 1930s; now one of the most competitive annual grasses in Midwest corn and soybean fields.",
  },
  "giant-ragweed": {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by large seeds moved by water tillage and wildlife; herbicide-resistant populations are increasingly dominant in Midwest crop fields.",
  },
  "golden-alexanders": {
    method: "native-spread",
    continent: "americas",
    story:
      "Native prairie perennial spreading by seeds dispersed by pollinators and gravity; a beneficial wildflower — distinguish from toxic Apiaceae look-alikes.",
  },
  Goosegrass: {
    method: "accident",
    continent: "africa",
    story:
      "Introduced from tropical Africa and Asia via contaminated crop and turfgrass seed; thrives in compacted soils and spreads rapidly in disturbed areas.",
  },
  "green-foxtail": {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Eurasia via contaminated grain shipments; wind- and water-dispersed seeds spread through pastures meadows and crop fields worldwide.",
  },
  Ground_ivy: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe as a medicinal herb; spreads by creeping stolons rooting at nodes forming persistent dense patches in gardens and disturbed areas.",
  },
  Hedge_bindweed: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by deep rhizomes and seeds along hedgerows riverbanks and roadsides; persistent rootstock makes it very hard to control.",
  },
  Hemp: {
    method: "purpose",
    continent: "asia",
    story:
      "Introduced from Central Asia for fiber and medicinal use; feral hemp persists from historical cultivation and spreads via seeds in disturbed areas.",
  },
  Hemp_dogbane: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by wind-dispersed seeds and creeping rhizomes; colonizes fields roadsides and riverbanks; toxic cardiac glycosides harm livestock.",
  },
  Henbit_deadnettle: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe and Asia via contaminated seed; a winter annual that spreads rapidly through gardens fields and roadsides in cool seasons.",
  },
  Honeyvine_Milkweed: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by wind-dispersed seeds and lateral rhizomes; climbs through crops and hedgerows along riverbanks across the Midwest.",
  },
  Horsenettle: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by deep rhizomes and bird-dispersed berries; colonizes pastures meadows and roadsides; toxic to livestock and humans.",
  },
  Horseweed: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native winter annual spreading via wind-dispersed seeds; herbicide-resistant biotypes spread rapidly across the Midwest via wind and farm machinery.",
  },
  Ivyleaf_morningglory: {
    method: "accident",
    continent: "americas",
    story:
      "Introduced from tropical America in contaminated crop seed; hard-coated seeds survive in soil for years and spread with harvest equipment.",
  },
  Jimsonweed: {
    method: "accident",
    continent: "americas",
    story:
      "Introduced from tropical Americas; spread via seed in contaminated soil and livestock dung through disturbed fields and roadsides; all parts highly toxic.",
  },
  johnsongrass: {
    method: "purpose",
    continent: "mediterranean",
    story:
      "Introduced from the Mediterranean as a forage grass in the 1830s; escaped cultivation via aggressive rhizomes and prolific seed; noxious in many states.",
  },
  kochia: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe and Asia as an ornamental in the 1800s; tumbleweed habit disperses 25000+ seeds across fields; rapidly develops herbicide resistance.",
  },
  Ladysthumb: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated crop seed; thrives in moist disturbed soils and spreads readily through fields gardens and waste areas.",
  },
  lambsquarters: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe by early settlers as an edible plant; prolific seed producer spreading through contaminated seed lots and disturbed soil.",
  },
  "large-crabgrass": {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Eurasia via contaminated crop and lawn seed; warm-season annual spreading by seeds moved in turfgrass sod farm equipment and water.",
  },
  Longspine_sandbur: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by spiny burs clinging to livestock fur clothing and vehicle tires dispersing seeds across sandy pastures and roadsides.",
  },
  Mouseear_chickweed: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated seed; a hairy perennial forming mats and spreading by seed and stem fragments across lawns fields and roadsides.",
  },
  Musk_thistle: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated forage and crop seed; wind-dispersed seeds enable rapid spread into pastures roadsides and range lands.",
  },
  Nimblewill: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by stolons and seeds; forms patches in lawns and woodlands often moved via contaminated sod and mowing equipment.",
  },
  "palmer-amaranth": {
    method: "other-species",
    continent: "americas",
    story:
      "Native to the southwestern US; spread eastward into Midwest croplands via contaminated hay cottonseed feed equipment livestock and irrigation water.",
  },
  "pennsylvania-smartweed": {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by prolific seeds dispersed by water and waterfowl; thrives in wet field areas and indicates poor drainage in low-lying cropland.",
  },
  Pinnate_tansymustard: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native winter annual spreading by abundant small seeds dispersed by wind and water; colonizes disturbed rangelands roadsides and open woodlands.",
  },
  "poison-hemlock": {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe and W Asia via contaminated seed or soil during early settlement; abundant seeds spread along ditches roadsides and stream banks.",
  },
  Prickly_lettuce: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated crop seed; wind-dispersed seeds colonize disturbed areas fallow fields and roadsides across North America.",
  },
  Prickly_sida: {
    method: "accident",
    continent: "americas",
    story:
      "Introduced from the Americas via contaminated soil and crop seed; persistent seeds and developing herbicide resistance are expanding its range in row crops.",
  },
  Quackgrass: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Eurasia via contaminated crop seed; creeping rhizomes and allelopathic roots enable rapid spread and persistence across croplands.",
  },
  Redroot_pigweed: {
    method: "accident",
    continent: "americas",
    story:
      "Introduced from tropical Americas via contaminated crop seed; prolific seed producer spreading through tillage wind and water across disturbed cropland.",
  },
  Russian_thistle: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Russia via contaminated flaxseed in the 1870s; tumbling mature plants disperse up to 100000 seeds across roadsides and disturbed fields.",
  },
  Scouringrush: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by spores and creeping rhizomes along riverbanks and wetlands; rhizome fragments spread via equipment; highly resistant to control.",
  },
  Shattercane_Sorghums: {
    method: "purpose",
    continent: "africa",
    story:
      "Introduced from Africa as a crop ancestor; volunteer escapes spread via shattering seed heads and cross-pollination with cultivated sorghum.",
  },
  Shepherds_Purse: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated crop seed; heart-shaped seed pods release seeds that spread through gardens disturbed areas and crop fields.",
  },
  Smooth_Groundcherry: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by wind-dispersed seeds and rhizome fragments; tillage distributes root pieces through disturbed cropland and prairies.",
  },
  Spotted_spurge: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by explosively ejected seeds further dispersed by ants and water; colonizes lawns gardens and roadsides across North America.",
  },
  Star_of_Bethlehem: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Mediterranean Europe as an ornamental bulb; spreads via bulb offsets and seeds into lawns meadows and woodland edges; all parts toxic.",
  },
  Tall_Hedge_Mustard: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe and Central Asia via contaminated seed and soil; spreads along roadsides railways and waste grounds through wind-dispersed seeds.",
  },
  Toothed_spurge: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by explosive seed dispersal and ant activity; seeds persist in soil and colonize disturbed cropland roadsides and gardens.",
  },
  velvetleaf: {
    method: "purpose",
    continent: "asia",
    story:
      "Introduced from China in the early 1700s for fiber production; escaped cultivation and spread via contaminated crop seed into corn and soybean fields.",
  },
  Venice_mallow: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from the Mediterranean region via contaminated seed; a warm-season annual spreading through roadsides gardens and crop fields.",
  },
  Water_smartweed: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by seeds and rhizomes; seeds dispersed by water and waterfowl through wetlands rice fields pond margins and ditches.",
  },
  waterhemp: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual spreading by prolific wind-dispersed seeds; herbicide-resistant biotypes expand rapidly via water equipment and contaminated seed lots.",
  },
  White_campion: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated crop and forage seed; nocturnal-blooming perennial spreading by seed through grain fields roadsides and meadows.",
  },
  "wild-oat": {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Eurasia via contaminated crop seed; closely mimics cultivated oats at early stages hindering detection until after establishment in grain fields.",
  },
  "wild-parsnip": {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe as a food and medicinal plant; escaped cultivation and spread via wind-dispersed seeds along roadsides; sap causes skin burns.",
  },
  Wild_buckwheat: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe in contaminated grain; persistent seeds spread through tillage machinery and crop-seed lots across grain fields and roadsides.",
  },
  Wild_Carrot: {
    method: "purpose",
    continent: "europe",
    story:
      "Introduced from Europe as a food plant; escaped cultivation and spread by wind- and animal-dispersed barbed seeds across meadows roadsides and pastures.",
  },
  "Wild_Four-o'clock": {
    method: "native-spread",
    continent: "americas",
    story:
      "Native perennial spreading by large wind-dispersed seeds and fleshy taproots; colonizes prairies disturbed areas and roadsides across the central US.",
  },
  Wild_mustard: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe in contaminated grain seed; single plants produce 3000+ seeds dispersed by harvesting equipment and water across grain fields.",
  },
  Witchgrass: {
    method: "native-spread",
    continent: "americas",
    story:
      "Native annual producing up to 50000 seeds per plant; breaks off as a tumbleweed at maturity dispersing seeds widely across disturbed soils and cropland.",
  },
  Woolly_cupgrass: {
    method: "accident",
    continent: "asia",
    story:
      "Introduced from East Asia likely via contaminated millet or sorghum seed; competitive in corn and sorghum fields spread by harvesting equipment.",
  },
  "yellow-foxtail": {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated grain; warm-season annual spreading through farm equipment water and livestock movement across crop fields.",
  },
  "yellow-nutsedge": {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Eurasia via contaminated soil and plant material; underground tubers persist for years and spread easily by tillage equipment.",
  },
  yellow_Rocket: {
    method: "accident",
    continent: "europe",
    story:
      "Introduced from Europe via contaminated hay and crop seed; forms dense patches in small grain fields and colonizes roadsides via wind-dispersed seeds.",
  },
};

/**
 * Most effective MOA for each weed (WSSA group number + name), sourced from the updated
 * extension/Take Action spreadsheet. NOTE: the source data now provides a single top MOA
 * per weed rather than a top-3 ranking, so this replaces the former 3-tuple structure.
 * "none" indicates the source notes no single MOA group is consistently reliable.
 */
export const WEED_TOP_MOA: Record<string, string> = {
  "annual-ryegrass": "accase",
  Asian_copperleaf: "ppo-post",
  Asiatic_dayflower: "als-post",
  barnyardgrass: "vlcfa-15",
  Buffalobur: "auxin",
  Burcucumber: "auxin",
  "canada-thistle": "auxin",
  caraway: "auxin",
  Catchweed_bedstraw: "auxin",
  "common-ragweed": "ppo-post",
  Common_Burdock: "auxin",
  common_Cocklebur: "ppo-post",
  Common_copperleaf: "ppo-post",
  Common_Mallow: "auxin",
  common_Milkweed: "auxin",
  Common_Morningglory: "ppo-post",
  Common_Mullein: "auxin",
  Common_Sunflower: "auxin",
  Common_teasel: "auxin",
  CommonChickweed: "psii-5",
  commonPokeweed: "auxin",
  Corn_speedwell: "psii-5",
  Curly_dock: "auxin",
  Dandelion: "auxin",
  Downy_brome: "als-post",
  Eastern_black_nightshade: "ppo-post",
  Fall_Panicum: "vlcfa-15",
  Field_bindweed: "auxin",
  Field_Horsetail: "none",
  Field_Pennycress: "auxin",
  Foxtail_barley: "accase",
  Garlic_mustard: "auxin",
  "giant-foxtail": "vlcfa-15",
  "giant-ragweed": "auxin",
  "golden-alexanders": "auxin",
  Goosegrass: "accase",
  "green-foxtail": "vlcfa-15",
  Ground_ivy: "auxin",
  Hedge_bindweed: "auxin",
  Hemp: "hppd",
  Hemp_dogbane: "auxin",
  Henbit_deadnettle: "psii-5",
  Honeyvine_Milkweed: "auxin",
  Horsenettle: "auxin",
  Horseweed: "ppo-post",
  Ivyleaf_morningglory: "ppo-post",
  Jimsonweed: "auxin",
  johnsongrass: "accase",
  kochia: "auxin",
  Ladysthumb: "auxin",
  lambsquarters: "psii-5",
  "large-crabgrass": "microtubule-3",
  Longspine_sandbur: "accase",
  Mouseear_chickweed: "auxin",
  Musk_thistle: "auxin",
  Nimblewill: "accase",
  "palmer-amaranth": "vlcfa-15",
  "pennsylvania-smartweed": "auxin",
  Pinnate_tansymustard: "auxin",
  "poison-hemlock": "auxin",
  Prickly_lettuce: "auxin",
  Prickly_sida: "ppo-post",
  Quackgrass: "epsps",
  Redroot_pigweed: "ppo-post",
  Russian_thistle: "auxin",
  Scouringrush: "none",
  Shattercane_Sorghums: "accase",
  Shepherds_Purse: "psii-5",
  Smooth_Groundcherry: "auxin",
  Spotted_spurge: "ppo-post",
  Star_of_Bethlehem: "auxin",
  Tall_Hedge_Mustard: "auxin",
  Toothed_spurge: "ppo-post",
  velvetleaf: "hppd",
  Venice_mallow: "ppo-post",
  Water_smartweed: "auxin",
  waterhemp: "vlcfa-15",
  White_campion: "auxin",
  "wild-oat": "accase",
  "wild-parsnip": "auxin",
  Wild_buckwheat: "auxin",
  Wild_Carrot: "auxin",
  "Wild_Four-o'clock": "auxin",
  Wild_mustard: "auxin",
  Witchgrass: "vlcfa-15",
  Woolly_cupgrass: "vlcfa-15",
  "yellow-foxtail": "vlcfa-15",
  "yellow-nutsedge": "als-post",
  yellow_Rocket: "auxin",
};

/**
 * Array-shaped view of WEED_TOP_MOA for consumers that expect a ranked list.
 * The source now provides one top MOA per weed, so each list has a single entry
 * ("none" entries are omitted).
 */
export const WEED_TOP_MOAS: Record<string, string[]> = Object.fromEntries(
  Object.entries(WEED_TOP_MOA)
    .filter(([, moa]) => moa && moa !== 'none')
    .map(([id, moa]) => [id, [moa]]),
);
